MyAspNLogDBApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace MyAspNLogDBApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MyAspNLogDBApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyAspNLogDBApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

MyAspNLogDBApp/Pages/NLogTest.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace MyAspNLogDBApp.Pages
{
    /// <summary>
    /// class NLogTestModel
    /// We need:
    /// Install-Package NLog -Version 5.1.0
    /// Install-Package System.Data.SqlClient -Version 4.8.5
    /// Install-Package NLog.Database -Version 5.1.0  
    /// Install-Package NLog.Web.AspNetCore -Version 5.2.0
    /// </summary>
    public class NLogTestModel : PageModel
    {
        private readonly NLog.Logger _logger;

        public string? MessageText { get; set; }

        /// <summary>
        /// Construtor
        /// </summary>
        public NLogTestModel()
        {
            _logger = NLog.LogManager.GetCurrentClassLogger();
            NLog.GlobalDiagnosticsContext.Set("Application", "This is an example to store some text or other data in NLog");

            string message = "We are entering the Constructor of NLogTestModel : PageModel";
            _logger.Info(message);
        }

        /// <summary>
        /// OnGet
        /// </summary>
        public void OnGet()
        {
        }

        /******************************/
        /*       Button Events        */
        /******************************/
        #region Button Events

        /// <summary>
        /// OnGetButton_6
        /// </summary>
        public void OnGetButton_6()
        {
            CatchStackOverflow1();

            Debug.WriteLine($"Button_6");
        }
        public void CatchStackOverflow1()
        {
            try
            {
                throw new StackOverflowException();
            }
            catch (StackOverflowException ex)
            {
                // Executes and handles the exception.
                // User code continues
                _logger.Error(ex.ToString());
            }
        }

        /// <summary>
        /// OnGetButton_5
        /// This doesn't really work in C# and .Net see:
        /// https://learn.microsoft.com/en-us/archive/blogs/jaredpar/when-can-you-catch-a-stackoverflowexception
        /// </summary>
        public void OnGetButton_5()
        {
            try
            {
                Foo();
            }
            catch (Exception ex)
            {
                _logger.Error(ex.ToString());                
            }

            Debug.WriteLine($"Button_5");
        }

        /// <summary>
        /// OnGetButton_4
        /// </summary>
        public void OnGetButton_4()
        {
            int b = 1, c = 0;

            try
            {
                int a = b / c;
            }
            catch (Exception ex)
            {
                _logger.Error(ex.ToString());
            }

            Debug.WriteLine($"Button_4");
        }

        /// <summary>
        /// OnGetButton_3
        /// </summary>
        public void OnGetButton_3()
        {
            Exception myExcetion = new("MyException");

            try
            {
                throw myExcetion;
            }
            catch (Exception ex)
            {
                _logger.Error(ex.ToString());
            }

            Debug.WriteLine($"Button_3");
        }

        /// <summary>
        /// OnGetButton_2
        /// </summary>
        public void OnGetButton_2()
        {
            string message = "You pressed Button #2 and create an Error Message Beep()";
            _logger.Error(message);

            Debug.WriteLine($"Button_2");
        }

        /// <summary>
        /// OnGetButton_1
        /// </summary>
        public void OnGetButton_1()
        {
            string message = "You pressed Button #1";
            string user = "User XYZ";
            _logger.WithProperty("AppUser", user).Info(message);

            Debug.WriteLine($"Button_1");
        }

        #endregion
        /******************************/
        /*      Other Events          */
        /******************************/
        #region Other Events

        /// <summary>
        /// OnPost
        /// </summary>
        public void OnPost()
        {
            var messageText = Request.Form["MessageText"];
            if (!String.IsNullOrEmpty(messageText))
                Debug.WriteLine($"MessageText is {messageText}");

            string message = messageText;
            _logger.Info(message);
        }

        #endregion
        /******************************/
        /*      Other Functions       */
        /******************************/
        #region Other Functions

        /// <summary>
        /// foo
        /// Just create a SackOverflow
        /// </summary>
        private void Foo()
        {
            Foo();
        }

        #endregion

    }
}

MyAspNLogDBApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyAspNLogDBApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MyAspNLogDBApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MyAspNLogDBApp/Pages/NLogTest.cshtml
@page
@model MyAspNLogDBApp.Pages.NLogTestModel
@{
    ViewData["Title"] = "NLogTest Page";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to test some NLog entries.</p>
<p>
    <div style="padding-top: 10px;">
        <button>
            <a asp-page-handler="Button_6" title="Create a user handled Stack Overflow" class="nav-link text-dark" asp>
                #6
            </a>
        </button>
    </div>
    <div style="padding-top: 10px;">
        <button>
            <a asp-page-handler="Button_5" title="Create a Stack Overflow, caution this is a real stack overflow terminating the application (see note in source code)" class="nav-link text-dark" asp>
                #5
            </a>
        </button>
    </div>
    <div style="padding-top: 10px;">
        <button>
            <a asp-page-handler="Button_4" title="Divide by 0" class="nav-link text-dark" asp>
                #4
            </a>
        </button>
    </div>
    <div style="padding-top: 10px;">
        <button>
            <a asp-page-handler="Button_3" title="Create an Exception" class="nav-link text-dark" asp>
                #3
            </a>
        </button>
    </div>
    <div style="padding-top: 10px;">
        <button>
            <a asp-page-handler="Button_2" title="Print a Error Message in the Log-File" class="nav-link text-dark" asp>
                #2
            </a>
        </button>
    </div>
    <div style="padding-top: 10px;">
        <button>
            <a asp-page-handler="Button_1" title="Just print a Info Message in the Log-File" class="nav-link text-dark">
                #1
            </a>
        </button>
    </div>
</p>

<p>Enter a Message Text and press Submit to write a message with NLog in the DB:</p>
<form method="post">
    <input type="text" name="MessageText">
    <input type="submit">
</form>

MyAspNLogDBApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyAspNLogDBApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyAspNLogDBApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MyAspNLogDBApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/NLogTest">NLogTest</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyAspNLogDBApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>